# Idea taken from https://github.com/jupyterlab-contrib/jupyterlab-contrib.github.io/blob/7d6e63d125a65a9b2991227277a4f443c21fac45/.github/ISSUE_TEMPLATE/help-with-maintenance.md
name: Volunteer to help maintain
description: Request access to a repository to maintain it.
title: ""
labels: ["maintain"]
assignees:
  - ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: textarea
    id: which
    attributes:
      label: Which Project
      description: Which xarray-contrib project do you want to help maintain. Please provide a link.
  - type: checkboxes
    id: what-to-do
    attributes:
      label: What do you want to do
      options:
        - label: Address reported issues and feature requests
        - label: Update a **Archived** repository to make it work on the latest Xarray version
        - label: Improve an extension (if so please describe, what you want to achieve)
  - type: checkboxes
    id: help-type
    attributes:
      label: Which level of help, would you need (choose one of)
      options:
        - label: Total beginner but enthusiast (you are more than welcome and we will help in your learning of the Xarray ecosystem)
        - label: Good reviews with tips would be appreciated
        - label: I am a experienced developer with Xarray ecosystem
  - type: textarea
    id: other
    attributes:
      label: Other Information
      description: Any other information you want to share
